[package]
name = "actix-web-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
serde = "1.0.196"
serde_derive = "1.0.196"
cargo-watch = "8.5.2"
actix-multipart = "0.6.1"
futures = "0.3.17"
#uuid = "0.8.1" #
#    "v4",                # Lets you generate random UUIDs
#    "fast-rng",          # Use a faster (but still sufficiently random) RNG
#    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
uuid = { version = "1.7", features = ["v4", "fast-rng", "macro-diagnostics"] }

